package com.example.skillcinema.presentation


const val VIEWED_MOVIES_PREFERENCES = "VIEWED_MOVIES_PREFERENCES"
const val VIEWED_MOVIES_SET = "VIEWED_MOVIES_SET"
const val INTERESTED_MOVIES_PREFERENCES = "INTERESTED_MOVIES_PREFERENCES"
const val INTERESTED_MOVIES_SET = "INTERESTED_MOVIES_SET"
const val FAVORITE_MOVIES_PREFERENCES = "FAVORITE_MOVIES_PREFERENCES"
const val FAVORITE_MOVIES_SET = "FAVORITE_MOVIES_SET"
const val WANT_TO_WATCH_MOVIES_PREFERENCES = "WANT_TO_WATCH_MOVIES_PREFERENCES"
const val WANT_TO_WATCH_MOVIES_SET = "WANT_TO_WATCH_MOVIES_SET"
const val COLLECTION_PREFERENCES = "COLLECTION_PREFERENCES"
const val COLLECTION_PREFERENCES_SET = "COLLECTION_PREFERENCES_SET"
